SET SERVEROUTPUT ON

DECLARE
  -- Function to drop user and return 1 if dropped successfully or 0 if an exception occurs
  v_user_exists NUMBER;
  v_role_exists NUMBER;
BEGIN
  -- Drop users if they already exist
  v_user_exists := drop_user('DOCTOR_USER');
  v_user_exists := drop_user('NURSE_USER');
  v_user_exists := drop_user('PATIENT_USER');
  v_user_exists := drop_user('DONOR_USER');
  v_user_exists := drop_user('ADMIN_USER');
  
  -- Drop roles if they already exist
  v_role_exists := drop_role('DOCTOR_ROLE');
  v_role_exists := drop_role('NURSE_ROLE');
  v_role_exists := drop_role('PATIENT_ROLE');
  v_role_exists := drop_role('DONOR_ROLE');
  v_role_exists := drop_role('ADMIN_ROLE');

  -- Create roles
  EXECUTE IMMEDIATE 'CREATE ROLE DOCTOR_ROLE';
  DBMS_OUTPUT.PUT_LINE('Created DOCTOR_ROLE');
  EXECUTE IMMEDIATE 'CREATE ROLE NURSE_ROLE';
  DBMS_OUTPUT.PUT_LINE('Created NURSE_ROLE');
  EXECUTE IMMEDIATE 'CREATE ROLE PATIENT_ROLE';
  DBMS_OUTPUT.PUT_LINE('Created PATIENT_ROLE');
  EXECUTE IMMEDIATE 'CREATE ROLE DONOR_ROLE';
  DBMS_OUTPUT.PUT_LINE('Created DONOR_ROLE');
  EXECUTE IMMEDIATE 'CREATE ROLE ADMIN_ROLE';
  DBMS_OUTPUT.PUT_LINE('Created ADMIN_ROLE');

  -- Create users
  EXECUTE IMMEDIATE 'CREATE USER DOCTOR_USER IDENTIFIED BY passDoctor2024#';
  DBMS_OUTPUT.PUT_LINE('Created DOCTOR_USER');
  EXECUTE IMMEDIATE 'CREATE USER NURSE_USER IDENTIFIED BY passNurse2024#';
  DBMS_OUTPUT.PUT_LINE('Created NURSE_USER');
  EXECUTE IMMEDIATE 'CREATE USER PATIENT_USER IDENTIFIED BY passPatient2024#';
  DBMS_OUTPUT.PUT_LINE('Created PATIENT_USER');
  EXECUTE IMMEDIATE 'CREATE USER DONOR_USER IDENTIFIED BY passDonor2024#';
  DBMS_OUTPUT.PUT_LINE('Created DONOR_USER');
  EXECUTE IMMEDIATE 'CREATE USER ADMIN_USER IDENTIFIED BY passAdmin2024#';
  DBMS_OUTPUT.PUT_LINE('Created ADMIN_USER');

  -- Grant table permissions
  -- Doctor permissions
  EXECUTE IMMEDIATE 'GRANT SELECT ON HEALTH_REPORT TO DOCTOR_ROLE';
  EXECUTE IMMEDIATE 'GRANT SELECT ON APPOINTMENT TO DOCTOR_ROLE';
  EXECUTE IMMEDIATE 'GRANT SELECT ON DONOR_BLOOD_CAMP_ASSO TO DOCTOR_ROLE';
  DBMS_OUTPUT.PUT_LINE('Granted permissions to DOCTOR_ROLE');

  -- Nurse permissions
  EXECUTE IMMEDIATE 'GRANT SELECT, UPDATE (WEIGHT, BP, PULSE) ON HEALTH_REPORT TO NURSE_ROLE';
  EXECUTE IMMEDIATE 'GRANT SELECT ON APPOINTMENT TO NURSE_ROLE';
  DBMS_OUTPUT.PUT_LINE('Granted permissions to NURSE_ROLE');

  -- Patient permissions
  EXECUTE IMMEDIATE 'GRANT SELECT ON HEALTH_REPORT TO PATIENT_ROLE';
  EXECUTE IMMEDIATE 'GRANT SELECT ON PATIENT TO PATIENT_ROLE';
  DBMS_OUTPUT.PUT_LINE('Granted permissions to PATIENT_ROLE');

  -- Donor permissions
  EXECUTE IMMEDIATE 'GRANT SELECT ON DONOR_BLOOD_CAMP_ASSO TO DONOR_ROLE';
  DBMS_OUTPUT.PUT_LINE('Granted permissions to DONOR_ROLE');

  -- Admin permissions
  EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON APPOINTMENT TO ADMIN_ROLE';
  EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON BLOOD_CAMP TO ADMIN_ROLE';
  EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON BLOOD_REQUIREMENT TO ADMIN_ROLE';
  EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON CONTACT_DETAILS TO ADMIN_ROLE';
  EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON DEPTARTMENT TO ADMIN_ROLE';
  EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON DOCTOR TO ADMIN_ROLE';
  EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON DONOR TO ADMIN_ROLE';
  EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON DONOR_BLOOD_CAMP_ASSO TO ADMIN_ROLE';
  EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON HEALTH_REPORT TO ADMIN_ROLE';
  EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON IN_PATIENT TO ADMIN_ROLE';
  EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON MEDICINE TO ADMIN_ROLE';
  EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON NURSE TO ADMIN_ROLE';
  EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON OUT_PATIENT TO ADMIN_ROLE';
  EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON PATIENT TO ADMIN_ROLE';
  EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON PERSON TO ADMIN_ROLE';
  EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON PRESCRIPTION TO ADMIN_ROLE';
  EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON SHIFT_NURSE TO ADMIN_ROLE';
  DBMS_OUTPUT.PUT_LINE('Granted permissions to ADMIN_ROLE');

  -- Assign permissions to roles
  EXECUTE IMMEDIATE 'GRANT DOCTOR_ROLE TO DOCTOR_USER';
  EXECUTE IMMEDIATE 'GRANT NURSE_ROLE TO NURSE_USER';
  EXECUTE IMMEDIATE 'GRANT PATIENT_ROLE TO PATIENT_USER';
  EXECUTE IMMEDIATE 'GRANT DONOR_ROLE TO DONOR_USER';
  EXECUTE IMMEDIATE 'GRANT ADMIN_ROLE TO ADMIN_USER';
  DBMS_OUTPUT.PUT_LINE('Assigned roles to users');
END;
/
